# Docker Compose for Ahava Healthcare Platform
# Use this file if you have Docker Desktop installed
#
# Quick Start:
#   1. Install Docker Desktop: https://www.docker.com/products/docker-desktop/
#   2. Run: docker-compose up -d
#   3. Check status: docker-compose ps
#
version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: ahava-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ahava_user
      POSTGRES_PASSWORD: ahava_dev_password
      POSTGRES_DB: ahava-healthcare
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ahava_user -d ahava-healthcare"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache & Queue
  redis:
    image: redis:7-alpine
    container_name: ahava-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ahava_redis_pass
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  default:
    name: ahava-network


