import PDFDocument from 'pdfkit';

export interface MedicationLine {
  name: string;
  dosage: string;
  frequency: string;
  duration: string;
  instructions?: string;
}

export interface PrescriptionData {
  id: string;
  issuedAt: Date;
  doctor: { firstName: string; lastName: string; hcpsaNumber?: string | null };
  patient: { firstName: string; lastName: string; dateOfBirth?: Date | null };
  diagnosis: string;
  medications: MedicationLine[];
  doctorNotes?: string | null;
}

export interface ReferralData {
  id: string;
  issuedAt: Date;
  referralType: string;
  recommendedFacility: string;
  provisionalDiagnosis: string;
  clinicalNotes: string;
  doctor: { firstName: string; lastName: string; hcpsaNumber?: string | null };
  patient: { firstName: string; lastName: string; dateOfBirth?: Date | null; phone?: string | null };
}

// Shared header for all Ahava documents
function drawHeader(doc: InstanceType<typeof PDFDocument>, title: string) {
  doc.rect(0, 0, doc.page.width, 80).fill('#0d2f5e');
  doc.fontSize(18).fillColor('white').font('Helvetica-Bold')
    .text('Ahava Healthcare Platform', 40, 22);
  doc.fontSize(10).fillColor('#93c5fd').font('Helvetica')
    .text('Confidential Medical Document — POPIA Compliant', 40, 46);
  doc.fontSize(13).fillColor('white').font('Helvetica-Bold')
    .text(title, doc.page.width - 220, 30, { width: 180, align: 'right' });
  doc.fillColor('#1c1917');
}

function drawFooter(doc: InstanceType<typeof PDFDocument>) {
  const y = doc.page.height - 50;
  doc.moveTo(40, y).lineTo(doc.page.width - 40, y).strokeColor('#e2e8f0').lineWidth(1).stroke();
  doc.fontSize(8).fillColor('#94a3b8').font('Helvetica')
    .text(
      'This document was generated by Ahava Healthcare Platform. It is a legally valid clinical document under the Health Professions Act 56 of 1974. ' +
      'Stored securely in accordance with POPIA. For platform support: support@ahavaon88.co.za',
      40, y + 8, { width: doc.page.width - 80, align: 'center' }
    );
}

function sectionLabel(doc: InstanceType<typeof PDFDocument>, label: string, y: number) {
  doc.fontSize(8).fillColor('#64748b').font('Helvetica-Bold')
    .text(label.toUpperCase(), 40, y);
}

function sectionValue(doc: InstanceType<typeof PDFDocument>, value: string, y: number, opts?: object) {
  doc.fontSize(11).fillColor('#0f172a').font('Helvetica')
    .text(value, 40, y + 12, { width: doc.page.width - 80, ...(opts ?? {}) });
}

export function generatePrescriptionPdf(data: PrescriptionData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 40, size: 'A4' });
    const chunks: Buffer[] = [];
    doc.on('data', (c: Buffer) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    drawHeader(doc, 'PRESCRIPTION');

    // Reference block
    doc.fontSize(9).fillColor('#64748b').font('Helvetica')
      .text(`Ref: RX-${data.id.slice(-8).toUpperCase()}`, 40, 96)
      .text(`Date: ${new Date(data.issuedAt).toLocaleDateString('en-ZA', { day: '2-digit', month: 'long', year: 'numeric' })}`, doc.page.width - 200, 96, { width: 160, align: 'right' });

    // Divider
    doc.moveTo(40, 114).lineTo(doc.page.width - 40, 114).strokeColor('#e2e8f0').lineWidth(1).stroke();

    // Two-column: Prescriber | Patient
    const col1 = 40;
    const col2 = doc.page.width / 2 + 10;
    let y = 124;

    doc.rect(col1 - 4, y - 4, doc.page.width / 2 - 20, 70).fill('#f8fafc');
    doc.fontSize(8).fillColor('#1e40af').font('Helvetica-Bold').text('PRESCRIBING PRACTITIONER', col1, y);
    y += 14;
    doc.fontSize(11).fillColor('#0f172a').font('Helvetica-Bold')
      .text(`Dr. ${data.doctor.firstName} ${data.doctor.lastName}`, col1, y);
    y += 16;
    doc.fontSize(10).fillColor('#374151').font('Helvetica')
      .text(`HPCSA Practice No: ${data.doctor.hcpsaNumber || 'PENDING VERIFICATION'}`, col1, y);
    y += 14;
    doc.fontSize(9).fillColor('#64748b').text('Ahava Healthcare Platform', col1, y);

    y = 124;
    doc.rect(col2 - 4, y - 4, doc.page.width / 2 - 36, 70).fill('#f0fdf4');
    doc.fontSize(8).fillColor('#166534').font('Helvetica-Bold').text('PATIENT', col2, y);
    y += 14;
    doc.fontSize(11).fillColor('#0f172a').font('Helvetica-Bold')
      .text(`${data.patient.firstName} ${data.patient.lastName}`, col2, y);
    y += 16;
    if (data.patient.dateOfBirth) {
      doc.fontSize(10).fillColor('#374151').font('Helvetica')
        .text(`DOB: ${new Date(data.patient.dateOfBirth).toLocaleDateString('en-ZA')}`, col2, y);
    }

    y = 210;
    doc.moveTo(40, y).lineTo(doc.page.width - 40, y).strokeColor('#e2e8f0').lineWidth(1).stroke();

    // Diagnosis
    y += 14;
    sectionLabel(doc, 'Clinical Diagnosis', y);
    sectionValue(doc, data.diagnosis, y);
    y += 44;

    // Medications table
    doc.fontSize(8).fillColor('#1e40af').font('Helvetica-Bold').text('PRESCRIBED MEDICATIONS', 40, y);
    y += 14;

    const headers = ['Medication', 'Dosage', 'Frequency', 'Duration'];
    const colWidths = [170, 90, 110, 90];
    const startX = [40, 210, 300, 410];

    doc.rect(40, y, doc.page.width - 80, 18).fill('#0d2f5e');
    headers.forEach((h, i) => {
      doc.fontSize(8).fillColor('white').font('Helvetica-Bold').text(h, startX[i], y + 5, { width: colWidths[i] });
    });
    y += 18;

    (data.medications as MedicationLine[]).forEach((med, idx) => {
      const rowBg = idx % 2 === 0 ? '#f8fafc' : '#ffffff';
      doc.rect(40, y, doc.page.width - 80, 22).fill(rowBg);
      doc.fontSize(9).fillColor('#0f172a').font('Helvetica-Bold').text(med.name, startX[0], y + 7, { width: colWidths[0] });
      doc.fontSize(9).fillColor('#374151').font('Helvetica').text(med.dosage, startX[1], y + 7, { width: colWidths[1] });
      doc.text(med.frequency, startX[2], y + 7, { width: colWidths[2] });
      doc.text(med.duration, startX[3], y + 7, { width: colWidths[3] });
      y += 22;
      if (med.instructions) {
        doc.fontSize(8).fillColor('#64748b').font('Helvetica').text(`  Instructions: ${med.instructions}`, startX[0] + 4, y, { width: doc.page.width - 100 });
        y += 14;
      }
    });

    y += 14;
    doc.moveTo(40, y).lineTo(doc.page.width - 40, y).strokeColor('#e2e8f0').lineWidth(1).stroke();

    if (data.doctorNotes) {
      y += 14;
      sectionLabel(doc, 'Additional Notes', y);
      sectionValue(doc, data.doctorNotes, y);
      y += 36;
    }

    // Signature block
    y = Math.max(y + 30, doc.page.height - 160);
    doc.moveTo(40, y).lineTo(220, y).strokeColor('#0d2f5e').lineWidth(1).stroke();
    doc.fontSize(9).fillColor('#374151').font('Helvetica')
      .text(`Dr. ${data.doctor.firstName} ${data.doctor.lastName}`, 40, y + 6)
      .text(`HPCSA: ${data.doctor.hcpsaNumber || 'Pending'}`, 40, y + 18)
      .text('Authorised Prescriber', 40, y + 30);

    doc.fontSize(8).fillColor('#94a3b8')
      .text('This prescription is valid for 30 days from date of issue. Schedule 0-4 medications only.', 40, y + 50, { width: doc.page.width - 80 });

    drawFooter(doc);
    doc.end();
  });
}

export function generateReferralPdf(data: ReferralData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 40, size: 'A4' });
    const chunks: Buffer[] = [];
    doc.on('data', (c: Buffer) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const isEmergency = data.referralType === 'EMERGENCY';
    drawHeader(doc, isEmergency ? '🚨 EMERGENCY REFERRAL' : 'MEDICAL REFERRAL LETTER');

    if (isEmergency) {
      doc.rect(0, 80, doc.page.width, 22).fill('#dc2626');
      doc.fontSize(11).fillColor('white').font('Helvetica-Bold')
        .text('⚠  URGENT — Present this document immediately at any emergency facility', 0, 85, { align: 'center' });
    }

    const topY = isEmergency ? 116 : 96;
    doc.fontSize(9).fillColor('#64748b').font('Helvetica')
      .text(`Ref: REF-${data.id.slice(-8).toUpperCase()}`, 40, topY)
      .text(`Date: ${new Date(data.issuedAt).toLocaleDateString('en-ZA', { day: '2-digit', month: 'long', year: 'numeric' })}`, doc.page.width - 200, topY, { width: 160, align: 'right' });

    doc.moveTo(40, topY + 18).lineTo(doc.page.width - 40, topY + 18).strokeColor('#e2e8f0').lineWidth(1).stroke();

    let y = topY + 32;

    // Referring doctor box
    doc.rect(40, y, doc.page.width - 80, 60).fill('#f8fafc');
    doc.fontSize(8).fillColor('#1e40af').font('Helvetica-Bold').text('REFERRING PRACTITIONER', 50, y + 8);
    doc.fontSize(11).fillColor('#0f172a').font('Helvetica-Bold').text(`Dr. ${data.doctor.firstName} ${data.doctor.lastName}`, 50, y + 20);
    doc.fontSize(10).fillColor('#374151').font('Helvetica').text(`HPCSA Practice No: ${data.doctor.hcpsaNumber || 'PENDING VERIFICATION'}`, 50, y + 34);
    doc.fontSize(9).fillColor('#64748b').text('Ahava Healthcare Platform (Telemedicine)', 50, y + 46);
    y += 74;

    // Patient box
    doc.rect(40, y, doc.page.width - 80, 60).fill('#f0fdf4');
    doc.fontSize(8).fillColor('#166534').font('Helvetica-Bold').text('PATIENT DETAILS', 50, y + 8);
    doc.fontSize(11).fillColor('#0f172a').font('Helvetica-Bold').text(`${data.patient.firstName} ${data.patient.lastName}`, 50, y + 20);
    const dobStr = data.patient.dateOfBirth ? new Date(data.patient.dateOfBirth).toLocaleDateString('en-ZA') : 'Not provided';
    doc.fontSize(10).fillColor('#374151').font('Helvetica').text(`Date of Birth: ${dobStr}`, 50, y + 34);
    if (data.patient.phone) {
      doc.text(`Contact: ${data.patient.phone}`, 50, y + 46);
    }
    y += 74;

    doc.moveTo(40, y).lineTo(doc.page.width - 40, y).strokeColor('#e2e8f0').lineWidth(1).stroke();
    y += 16;

    // Referral details
    const urgencyColour = isEmergency ? '#dc2626' : data.referralType === 'URGENT' ? '#d97706' : '#059669';
    doc.rect(40, y, 140, 24).fill(urgencyColour);
    doc.fontSize(10).fillColor('white').font('Helvetica-Bold')
      .text(`${data.referralType} REFERRAL`, 44, y + 8, { width: 136 });
    doc.fontSize(10).fillColor('#374151').font('Helvetica')
      .text(`Recommended facility: ${data.recommendedFacility}`, 196, y + 8);
    y += 36;

    sectionLabel(doc, 'Provisional Diagnosis', y);
    doc.fontSize(12).fillColor('#0f172a').font('Helvetica-Bold').text(data.provisionalDiagnosis, 40, y + 12);
    y += 36;

    sectionLabel(doc, 'Clinical Assessment & Referral Notes', y);
    doc.fontSize(10).fillColor('#1e293b').font('Helvetica')
      .text(data.clinicalNotes, 40, y + 12, { width: doc.page.width - 80, lineGap: 3 });

    const notesHeight = doc.heightOfString(data.clinicalNotes, { width: doc.page.width - 80 });
    y += 12 + notesHeight + 24;

    doc.moveTo(40, y).lineTo(doc.page.width - 40, y).strokeColor('#e2e8f0').lineWidth(1).stroke();
    y += 16;

    // Emergency contacts
    doc.rect(40, y, doc.page.width - 80, 40).fill(isEmergency ? '#fef2f2' : '#f0f9ff');
    doc.fontSize(8).fillColor(isEmergency ? '#dc2626' : '#0369a1').font('Helvetica-Bold')
      .text('SA EMERGENCY CONTACTS', 50, y + 8);
    doc.fontSize(9).fillColor('#374151').font('Helvetica')
      .text('Emergency Medical Services: 10177  |  National Emergency: 112  |  Poison Centre: 0861 555 777', 50, y + 20);
    y += 54;

    // Signature
    doc.moveTo(40, y).lineTo(220, y).strokeColor('#0d2f5e').lineWidth(1).stroke();
    doc.fontSize(9).fillColor('#374151').font('Helvetica')
      .text(`Dr. ${data.doctor.firstName} ${data.doctor.lastName}`, 40, y + 6)
      .text(`HPCSA: ${data.doctor.hcpsaNumber || 'Pending'}`, 40, y + 18)
      .text('Referring Practitioner', 40, y + 30);

    doc.fontSize(8).fillColor('#64748b').font('Helvetica')
      .text('Electronically issued via Ahava Healthcare Platform. Valid as a medical referral under the National Health Act 61 of 2003.', 40, y + 50, { width: doc.page.width - 80 });

    drawFooter(doc);
    doc.end();
  });
}
